version: "3.7"
services:
  rabbit1:
    image: rabbitmq:management
    hostname: rabbit1
    environment:
      RABBITMQ_ERLANG_COOKIE: "secret string"
      RABBITMQ_NODENAME: rabbit1
    volumes:
#      - "/data/rabbitmq1:/var/lib/rabbitmq"
      - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
      - "./definitions.json:/etc/rabbitmq/definitions.json"
    ports:
      - "14369:4369"
      - "5771:5671"
      - "5772:5672"
      - "16671:15671"
      - "16672:15672"
      - "26672:25672"

  rabbit2:
    image: rabbitmq:management
    hostname: rabbit2
    depends_on:
      - rabbit1
    environment:
      RABBITMQ_ERLANG_COOKIE: "secret string"
      RABBITMQ_NODENAME: rabbit2
    volumes:
#      - "/data/rabbitmq1:/var/lib/rabbitmq"
      - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
      - "./definitions.json:/etc/rabbitmq/definitions.json"
    
  rabbit3:
    image: rabbitmq:management
    hostname: rabbit3
    depends_on:
      - rabbit1
    environment:
      RABBITMQ_ERLANG_COOKIE: "secret string"
      RABBITMQ_NODENAME: rabbit3
    volumes:
#      - "/data/rabbitmq1:/var/lib/rabbitmq"
      - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
      - "./definitions.json:/etc/rabbitmq/definitions.json"

networks:
  default:
    external:
      name: rabbitmq-cluster
